seed: 42

model:
  #path: /root/autodl-tmp/css/model_weights/llama3.1_8b/models--meta-llama--Llama-3.1-8B/snapshots/d04e592bb4f6aa9cfee91e2e20afa771667e1d4b
  path: /root/autodl-tmp/css/model_weights/llama2_7b/models--meta-llama--Llama-2-7B-hf/snapshots/01c7f73d771dfac7d292323805ebc428287df4f9
  layer: 22  
  max_length: 512

data:
  hf_name: declare-lab/CategoricalHarmfulQA
  split: en
  total_samples: 200
  subcategories:
    - all

output_dir: ./outputs_llama2/pku_run_layer22
